service: sls-template-v2
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-south-1
  memorySize: 128
  timeout: 10
  logRetentionInDays: 7
  environment:
    APP_ENV: ${self:provider.stage}
    MYSQL_HOST: ${env:MYSQL_HOST_${self:provider.stage}}
    MYSQL_PORT: ${env:MYSQL_PORT_${self:provider.stage}}
    MYSQL_USER: ${env:MYSQL_USER_${self:provider.stage}}
    MYSQL_PASS: ${env:MYSQL_PASS_${self:provider.stage}}
    MYSQL_DBNAME: ${env:MYSQL_DBNAME_${self:provider.stage}}

package:
  individually: true

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    minify: true

functions:
  users:
    handler: index.UserController
    events:
      - http:
          path: /users
          method: GET
      - http:
          path: /users
          method: POST
