service: sls-upload-media
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-south-1
  memorySize: 128
  timeout: 10
  logRetentionInDays: 7
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:Put*"
            - "s3:Get*"
          Resource:
            - arn:aws:s3:::${self:custom.bucket}/*
  environment:
    APP_ENV: ${self:provider.stage}
    BUCKETNAME: ${self:custom.bucket}

package:
  individually: true

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  bucket: upload-${self:provider.stage}-artifacts
  esbuild:
    minify: true

functions:
  upload:
    handler: src/handler.app
    events:
      - http:
          path: /initalize
          method: POST
      - http:
          path: /get-presigned-urls
          method: POST
      - http:
          path: /finalize
          method: POST

resources:
  Resources:
    UploadDevArtifacts:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
        AccessControl: Private